aws ecr get-login --region us-west-2
docker build -t performance .
docker tag performance:latest 628897842239.dkr.ecr.us-west-2.amazonaws.com/performance:latest
docker push 628897842239.dkr.ecr.us-west-2.amazonaws.com/performance:latest
